# bin2h.cmake: embed a binary file as a C++ header (M5: SPIR-V blobs for the
# framework-free vkcheck harness, replacing Qt's resource system).
#
# Usage: cmake -DIN=<file> -DOUT=<header> -DNAME=<symbol> -P bin2h.cmake
# Emits: alignas(4) inline constexpr unsigned char <symbol>[];
#        inline constexpr std::size_t <symbol>_size;
# The 4-byte alignment matters: vkCreateShaderModule reads the array as
# uint32_t words.

if(NOT IN OR NOT OUT OR NOT NAME)
    message(FATAL_ERROR "bin2h.cmake needs -DIN=, -DOUT=, -DNAME=")
endif()

file(READ "${IN}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _bytes "${_hexlen} / 2")

# 0xNN, pairs, wrapped every 16 bytes for readable diffs.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _arr "${_hex}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " _arr "${_arr}")

get_filename_component(_in_name "${IN}" NAME)
file(WRITE "${OUT}"
"// Generated by tools/cmake/bin2h.cmake from ${_in_name} -- do not edit.
#pragma once

#include <cstddef>

alignas(4) inline constexpr unsigned char ${NAME}[] = {
    ${_arr}
};
inline constexpr std::size_t ${NAME}_size = ${_bytes};
")
