// Offline code generator: solves the exact prolate-spheroidal H2+ atlas
// (ses.spheroidal) across the whole snapped-R slider range and emits it as a
// constexpr data module (core/src/h2plus_atlas_data.ixx). The scene then
// LOADS the baked atlas -- zero runtime ODE solve. Regenerate with:
//   sesolver_genatlas core/src/h2plus_atlas_data.ixx
// (This is our own physics codegen, in the spirit of the offline slangc bake.)

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <string>
#include <vector>

import ses.spheroidal;

namespace {

constexpr int kProf = 48;    // baked profile samples (linear-interp synthesis)
constexpr int kMaxOrb = 16;  // exposed orbitals per R (representability caps it)
// R grid = the scene's 2h SNAP grid (must match kH2pBox/kH2pPoints in
// molecule_director), so every slider stop loads its EXACT baked atlas and
// the synthesized orbital matches the nuclei-on-grid-point potential.
constexpr double kH2pBox = 30.0;
constexpr int kH2pPoints = 256;
constexpr double kTwoH = 2.0 * kH2pBox / kH2pPoints;  // 0.234375
constexpr int kMlo = 4;   // round(1.0 / 2h)
constexpr int kMhi = 34;  // round(8.0 / 2h)

// Linear resample of a uniform-grid profile to n_out points (endpoints kept).
std::vector<double> resample(const std::vector<double>& y, int n_out) {
    std::vector<double> out(static_cast<std::size_t>(n_out), 0.0);
    const int n = static_cast<int>(y.size());
    if (n == 0) {
        return out;
    }
    for (int i = 0; i < n_out; ++i) {
        const double t = (n_out == 1) ? 0.0
                                      : static_cast<double>(i) * (n - 1) /
                                            (n_out - 1);
        const int lo = std::clamp(static_cast<int>(t), 0, n - 2);
        const double f = t - lo;
        out[static_cast<std::size_t>(i)] =
            y[static_cast<std::size_t>(lo)] * (1.0 - f) +
            y[static_cast<std::size_t>(lo + 1)] * f;
    }
    return out;
}

}  // namespace

int main(int argc, char** argv) {
    const std::string path =
        argc > 1 ? argv[1] : "core/src/h2plus_atlas_data.ixx";
    std::vector<double> rs;
    for (int m = kMlo; m <= kMhi; ++m) {
        rs.push_back(kTwoH * m);
    }
    const int nR = static_cast<int>(rs.size());

    FILE* f = std::fopen(path.c_str(), "w");
    if (f == nullptr) {
        std::fprintf(stderr, "gen: cannot open %s\n", path.c_str());
        return 1;
    }
    std::fprintf(f,
        "// GENERATED by sesolver_genatlas -- DO NOT EDIT.\n"
        "// The exact prolate-spheroidal H2+ atlas (ses.spheroidal), baked\n"
        "// across the R slider range so the scene loads instead of solving.\n"
        "// Regenerate: sesolver_genatlas core/src/h2plus_atlas_data.ixx\n"
        "module;\n#include <cmath>\n#include <cstddef>\n#include <vector>\n"
        "export module ses.h2plus_atlas_data;\nexport import ses.spheroidal;\n\n"
        "namespace ses::h2p_baked {\n"
        "constexpr int kNR = %d;\nconstexpr int kProf = %d;\n"
        "constexpr int kMaxOrb = %d;\n",
        nR, kProf, kMaxOrb);

    // R grid.
    std::fprintf(f, "constexpr double kRgrid[kNR] = {");
    for (int i = 0; i < nR; ++i) {
        std::fprintf(f, "%s%.6f", i ? "," : "", rs[static_cast<std::size_t>(i)]);
    }
    std::fprintf(f, "};\n");

    // Solve every R, capture the tables.
    std::vector<std::vector<ses::H2plusOrbital>> perR(static_cast<std::size_t>(nR));
    std::vector<int> counts(static_cast<std::size_t>(nR), 0);
    for (int i = 0; i < nR; ++i) {
        std::vector<ses::H2plusOrbital> atlas =
            ses::h2plus_atlas(rs[static_cast<std::size_t>(i)], kMaxOrb);
        if (static_cast<int>(atlas.size()) > kMaxOrb) {
            atlas.resize(kMaxOrb);
        }
        counts[static_cast<std::size_t>(i)] = static_cast<int>(atlas.size());
        perR[static_cast<std::size_t>(i)] = std::move(atlas);
        std::fprintf(stderr, "gen: R=%.3f -> %d orbitals\n",
                     rs[static_cast<std::size_t>(i)], counts[static_cast<std::size_t>(i)]);
    }

    std::fprintf(f, "constexpr int kCount[kNR] = {");
    for (int i = 0; i < nR; ++i) {
        std::fprintf(f, "%s%d", i ? "," : "", counts[static_cast<std::size_t>(i)]);
    }
    std::fprintf(f, "};\n");

    // Per-orbital scalars: m, n_eta, n_xi, parity, energy, xi_max.
    std::fprintf(f, "struct BakedOrb { int m, n_eta, n_xi, parity; "
                    "double energy, xi_max; };\n");
    std::fprintf(f, "constexpr BakedOrb kOrb[kNR][kMaxOrb] = {\n");
    for (int i = 0; i < nR; ++i) {
        std::fprintf(f, "{");
        for (int k = 0; k < kMaxOrb; ++k) {
            const ses::H2plusOrbital* o =
                k < counts[static_cast<std::size_t>(i)]
                    ? &perR[static_cast<std::size_t>(i)][static_cast<std::size_t>(k)]
                    : nullptr;
            const double xi_max = o && !o->xi.empty() ? o->xi.back() : 1.0;
            std::fprintf(f, "%s{%d,%d,%d,%d,%.8e,%.8e}", k ? "," : "",
                         o ? o->m : 0, o ? o->n_eta : 0, o ? o->n_xi : 0,
                         o ? o->parity : 1, o ? o->energy : 0.0, xi_max);
        }
        std::fprintf(f, "}%s\n", i + 1 < nR ? "," : "");
    }
    std::fprintf(f, "};\n");

    // Profiles M(eta), Lambda(xi) resampled to kProf.
    auto emit_profiles = [&](const char* name, bool radial) {
        std::fprintf(f, "constexpr double %s[kNR][kMaxOrb][kProf] = {\n", name);
        for (int i = 0; i < nR; ++i) {
            std::fprintf(f, "{");
            for (int k = 0; k < kMaxOrb; ++k) {
                std::fprintf(f, "%s{", k ? "," : "");
                std::vector<double> prof(static_cast<std::size_t>(kProf), 0.0);
                if (k < counts[static_cast<std::size_t>(i)]) {
                    const ses::H2plusOrbital& o =
                        perR[static_cast<std::size_t>(i)][static_cast<std::size_t>(k)];
                    prof = resample(radial ? o.lambda : o.M, kProf);
                }
                for (int p = 0; p < kProf; ++p) {
                    std::fprintf(f, "%s%.8e", p ? "," : "",
                                 prof[static_cast<std::size_t>(p)]);
                }
                std::fprintf(f, "}");
            }
            std::fprintf(f, "}%s\n", i + 1 < nR ? "," : "");
        }
        std::fprintf(f, "};\n");
    };
    emit_profiles("kM", false);
    emit_profiles("kLam", true);

    // Loader: nearest baked R -> reconstructed orbitals for synthesis.
    std::fprintf(f,
        "}  // namespace ses::h2p_baked\n\n"
        "export namespace ses {\n"
        "// The baked exact-atlas for the R nearest to the requested one.\n"
        "inline std::vector<H2plusOrbital> h2plus_atlas_baked(double R) {\n"
        "    using namespace h2p_baked;\n"
        "    int best = 0;\n"
        "    for (int i = 1; i < kNR; ++i) {\n"
        "        if (std::abs(kRgrid[i] - R) < std::abs(kRgrid[best] - R)) best = i;\n"
        "    }\n"
        "    std::vector<H2plusOrbital> out;\n"
        "    for (int k = 0; k < kCount[best]; ++k) {\n"
        "        const BakedOrb& b = kOrb[best][k];\n"
        "        H2plusOrbital o;\n"
        "        o.m = b.m; o.n_eta = b.n_eta; o.n_xi = b.n_xi;\n"
        "        o.parity = b.parity; o.energy = b.energy; o.R = kRgrid[best];\n"
        "        o.p = std::sqrt(std::max(0.0, -0.5 * b.energy * o.R * o.R));\n"
        "        o.eta.resize(kProf); o.M.resize(kProf);\n"
        "        o.xi.resize(kProf); o.lambda.resize(kProf);\n"
        "        const double deta = 2.0 / kProf;\n"
        "        const double dxi = (b.xi_max - 1.0) / kProf;\n"
        "        for (int p = 0; p < kProf; ++p) {\n"
        "            o.eta[static_cast<std::size_t>(p)] = -1.0 + (p + 0.5) * deta;\n"
        "            o.xi[static_cast<std::size_t>(p)] = 1.0 + (p + 0.5) * dxi;\n"
        "            o.M[static_cast<std::size_t>(p)] = kM[best][k][p];\n"
        "            o.lambda[static_cast<std::size_t>(p)] = kLam[best][k][p];\n"
        "        }\n"
        "        out.push_back(std::move(o));\n"
        "    }\n"
        "    return out;\n"
        "}\n"
        "}  // namespace ses\n");
    std::fclose(f);
    std::fprintf(stderr, "gen: wrote %s (%d R values)\n", path.c_str(), nR);
    return 0;
}
